// Right-rail AI panel (§4.3–4.6). Every surface here is AI-generated and
// carries the .ai-panel treatment + provenance + edit/flag actions — never
// presented as if it were the authors' words (§4.2 trust boundary).

import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import type { AiOutput, Tier } from '@shared/types';
import { api, ApiRequestError } from '../../api';
import { useAuth } from '../../auth';
import { AiBadge } from '../Badges';

function errMsg(err: unknown): string {
  return err instanceof ApiRequestError ? err.message : 'Something went wrong. Please try again.';
}

function parseGlossary(content: string): { term: string; definition: string }[] | null {
  try {
    const parsed: unknown = JSON.parse(content);
    return Array.isArray(parsed) ? (parsed as { term: string; definition: string }[]) : null;
  } catch {
    return null;
  }
}

function parseExplainer(content: string): { question: string; answer: string } | null {
  try {
    const parsed = JSON.parse(content) as { question?: unknown; answer?: unknown };
    if (parsed && typeof parsed.question === 'string' && typeof parsed.answer === 'string') {
      return { question: parsed.question, answer: parsed.answer };
    }
    return null;
  } catch {
    return null;
  }
}

function initialDraft(output: AiOutput): string {
  if (output.feature === 'summary') return output.content;
  try {
    return JSON.stringify(JSON.parse(output.content), null, 2);
  } catch {
    return output.content;
  }
}

function renderContent(output: AiOutput) {
  if (output.feature === 'summary') {
    return <p>{output.content}</p>;
  }
  if (output.feature === 'glossary') {
    const entries = parseGlossary(output.content);
    if (!entries) return <pre>{output.content}</pre>;
    return (
      <dl>
        {entries.map((entry, i) => (
          <div key={i} style={{ marginBottom: 'var(--space-2)' }}>
            <dt style={{ fontWeight: 'var(--font-weight-semibold)' }}>{entry.term}</dt>
            <dd>{entry.definition}</dd>
          </div>
        ))}
      </dl>
    );
  }
  const qa = parseExplainer(output.content);
  if (!qa) return <pre>{output.content}</pre>;
  return (
    <div>
      <p>
        <strong>Q:</strong> {qa.question}
      </p>
      <p>
        <strong>A:</strong> {qa.answer}
      </p>
    </div>
  );
}

function OutputCard({ output, onChange }: { output: AiOutput; onChange: () => void }) {
  const { user } = useAuth();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(() => initialDraft(output));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function save() {
    setBusy(true);
    setError(null);
    try {
      await api.patch(`/api/ai/${output.id}`, { content: draft });
      setEditing(false);
      onChange();
    } catch (err) {
      setError(errMsg(err));
    } finally {
      setBusy(false);
    }
  }

  async function flag() {
    const reason = window.prompt('Why are you flagging this AI output as inaccurate?');
    if (!reason || !reason.trim()) return;
    setBusy(true);
    setError(null);
    try {
      await api.post('/api/flags', { target_type: 'ai_output', target_id: output.id, reason: reason.trim() });
      onChange();
    } catch (err) {
      setError(errMsg(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div
      className="stack gap-2"
      style={{ paddingBottom: 'var(--space-3)', borderBottom: '1px solid var(--color-ai-soft-border)' }}
    >
      {editing ? (
        <div className="field">
          <label htmlFor={`ai-edit-${output.id}`}>Edit content</label>
          <textarea id={`ai-edit-${output.id}`} value={draft} onChange={(e) => setDraft(e.target.value)} rows={6} />
        </div>
      ) : (
        renderContent(output)
      )}

      {output.status !== 'active' ? (
        <p className="small" style={{ color: 'var(--color-warning)' }}>
          Status: {output.status}
        </p>
      ) : null}
      {error ? (
        <p className="small" style={{ color: 'var(--color-danger)' }}>
          {error}
        </p>
      ) : null}

      <footer className="ai-panel-footer">
        <p className="ai-panel-provenance">
          Generated by {output.model} · {output.model_version}
          {output.edited_by ? ` · edited ${output.edited_at?.slice(0, 10) ?? ''}` : ''} ·{' '}
          <Link to="/ai/track-record">view accuracy track record</Link>
        </p>
        {user ? (
          <div className="ai-panel-actions">
            {editing ? (
              <>
                <button className="btn btn-sm btn-ghost" type="button" onClick={() => void save()} disabled={busy}>
                  {busy ? 'Saving…' : 'Save'}
                </button>
                <button
                  className="btn btn-sm btn-ghost"
                  type="button"
                  onClick={() => {
                    setEditing(false);
                    setDraft(initialDraft(output));
                  }}
                  disabled={busy}
                >
                  Cancel
                </button>
              </>
            ) : (
              <button className="btn btn-sm btn-ghost" type="button" onClick={() => setEditing(true)}>
                Edit
              </button>
            )}
            <button className="btn btn-sm btn-ghost ai-panel-flag" type="button" onClick={() => void flag()} disabled={busy}>
              Flag inaccurate
            </button>
          </div>
        ) : (
          <Link to="/login" className="small">
            Log in to edit or flag
          </Link>
        )}
      </footer>
    </div>
  );
}

interface AiPanelProps {
  workId: number;
  tier: Tier;
  outputs: AiOutput[];
  onChange: () => void;
}

export default function AiPanel({ workId, tier, outputs, onChange }: AiPanelProps) {
  const { user } = useAuth();
  const [genBusy, setGenBusy] = useState<'summary' | 'glossary' | null>(null);
  const [genError, setGenError] = useState<string | null>(null);
  const [question, setQuestion] = useState('');
  const [askBusy, setAskBusy] = useState(false);
  const [askError, setAskError] = useState<string | null>(null);

  async function generate(feature: 'summary' | 'glossary') {
    setGenBusy(feature);
    setGenError(null);
    try {
      await api.post(`/api/works/${workId}/ai/${feature === 'summary' ? 'summarize' : 'glossary'}`);
      onChange();
    } catch (err) {
      setGenError(errMsg(err));
    } finally {
      setGenBusy(null);
    }
  }

  async function askExplain(e: FormEvent) {
    e.preventDefault();
    if (!question.trim()) return;
    setAskBusy(true);
    setAskError(null);
    try {
      await api.post(`/api/works/${workId}/ai/explain`, { question: question.trim() });
      setQuestion('');
      onChange();
    } catch (err) {
      setAskError(errMsg(err));
    } finally {
      setAskBusy(false);
    }
  }

  const summaries = outputs.filter((o) => o.feature === 'summary');
  const glossaries = outputs.filter((o) => o.feature === 'glossary');
  const explainers = outputs.filter((o) => o.feature === 'explainer');

  return (
    <section className="ai-panel" aria-label="AI-generated content">
      <header className="ai-panel-header" style={{ gap: 'var(--space-2)', justifyContent: 'space-between' }}>
        <span className="ai-panel-badge">AI-generated — not the authors&rsquo; words</span>
        <AiBadge label="AI" />
      </header>

      {tier !== 'C' ? (
        <p className="small">This work&rsquo;s license (Tier {tier}) limits AI to title + abstract (§4.3).</p>
      ) : null}

      <div className="ai-panel-body stack gap-4">
        {outputs.length === 0 ? (
          <p className="small muted">No AI-generated content yet for this work.</p>
        ) : (
          <>
            {summaries.length > 0 ? (
              <div className="stack gap-2">
                <h4>Summary</h4>
                {summaries.map((o) => (
                  <OutputCard key={o.id} output={o} onChange={onChange} />
                ))}
              </div>
            ) : null}
            {glossaries.length > 0 ? (
              <div className="stack gap-2">
                <h4>Glossary</h4>
                {glossaries.map((o) => (
                  <OutputCard key={o.id} output={o} onChange={onChange} />
                ))}
              </div>
            ) : null}
            {explainers.length > 0 ? (
              <div className="stack gap-2">
                <h4>Explainer Q&amp;A</h4>
                {explainers.map((o) => (
                  <OutputCard key={o.id} output={o} onChange={onChange} />
                ))}
              </div>
            ) : null}
          </>
        )}
      </div>

      {genError ? (
        <p className="small" style={{ color: 'var(--color-danger)' }}>
          {genError}
        </p>
      ) : null}

      {user ? (
        <>
          <div className="ai-panel-actions">
            <button className="btn btn-sm btn-ghost" type="button" onClick={() => void generate('summary')} disabled={genBusy !== null}>
              {genBusy === 'summary' ? 'Generating…' : 'Generate summary'}
            </button>
            <button className="btn btn-sm btn-ghost" type="button" onClick={() => void generate('glossary')} disabled={genBusy !== null}>
              {genBusy === 'glossary' ? 'Generating…' : 'Generate glossary'}
            </button>
          </div>
          <form className="field" onSubmit={(e) => void askExplain(e)}>
            <label htmlFor="ai-explain-question">Ask AI to explain</label>
            <div className="row gap-2">
              <input
                id="ai-explain-question"
                type="text"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                placeholder="What does this work mean by…?"
              />
              <button className="btn btn-sm btn-primary" type="submit" disabled={askBusy}>
                {askBusy ? 'Asking…' : 'Ask'}
              </button>
            </div>
            {askError ? (
              <p className="small" style={{ color: 'var(--color-danger)' }}>
                {askError}
              </p>
            ) : null}
          </form>
        </>
      ) : (
        <p className="small muted">
          <Link to="/login">Log in</Link> to generate AI summaries, glossaries, or ask questions.
        </p>
      )}
    </section>
  );
}
